version: '3.7'

services:

#  app:
#    image: 'shop-api-docker'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres
    volumes:
      - goreit-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
      - PGDATA=shop
    networks:
      - goreit

networks:
  goreit:

volumes:
  goreit-postgres-data: